all: mycolor mybufferMem

mycolor:
	g++ -o myColor buildITB/mColor.cpp buildITB/color.cpp -std=c++11

mybufferMem :
	g++ -o mybufferMem buildITB/bufferMem.cpp buildITB/mBufferMem.cpp -std=c++11

clean:
	$(RM) mycolor mybufferMem
